# Generated by Django 4.0.4 on 2023-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='set',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
