# Generated by Django 4.0.4 on 2023-10-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_alter_image_set_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='set',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
