# Generated by Django 4.0.4 on 2023-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_alter_image_set_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
